feat: add story divider
rnd500designs/capitalsphere-mui-sb8 pull request #1
Opened 2024-06-27 02:55 UTC by vinzkm

-add story for divider component
-include a theme for divider

2024-06-27 05:01 UTC, rnd500designs requested changes

2024-06-27 05:01 UTC, rnd500designs commented on src/theme/components/Divider.ts
for any color, refer to pallete.ts, or the standard way of theming the colors in MUI.
all hex or rgb values must be stored in reusable variables. :)

2024-06-27 05:01 UTC, rnd500designs commented on src/components/Divider.stories.tsx
in figma there's a subheader variant. you may include this in the variants and style per the mockup. 
part of the usage in diveder is on subheaders or section per the design system

2024-06-27 06:42 UTC, vinzkm commented on src/components/Divider.stories.tsx
just a clarification, can it be as a story (With Subheader story) instead? Then return a divider and a typography below it for that specific story. 
I was checking the divider's API if it includes a sub-header but the closest is the 'children' prop but it adds the text in the divider itself.

2024-06-28 00:21 UTC, rnd500designs requested changes

2024-06-28 00:21 UTC, rnd500designs commented on src/components/Divider.stories.tsx
just rename the story from "with subheader" to "Subheader " to match figma.
it means that the divider is for a subheader not necessarily having a sub header.
it seems to match the "inset" variant of the mui divider component.

2024-07-01 02:55 UTC, rnd500designs approved these changes

2024-07-01 03:39 UTC, merged